---
title: "report"
author: "Julia Chałasiak"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Extended Summary


```{r message=FALSE, warning=FALSE, include=FALSE}
libraries <- c("dplyr", "tidyr", "ggplot2", "readxl", "imputeTS", "vtable", "skimr", "DT", "caret", "gganimate", "patchwork", "ggpubr") 

r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

for (l in libraries) {
  if (!require(l)) install.packages(l); library(l, character.only = TRUE)
}

```


## Datasets Reading


```{r datasets_reading, message=FALSE, warning=FALSE}
currExchRates <- read.csv("./datasets/CurrencyExchangeRates.csv")
goldPrices <- read.csv("./datasets/Gold prices.csv")
spComposite <- read.csv("./datasets/S&P Composite.csv")
worldDevInd <- read_excel("./datasets/World_Development_Indicators.xlsx", trim_ws=TRUE, na = "..")
worldDevInd <- data.frame(worldDevInd)
btcMetadata <- read.csv("./datasets/BCHAIN_metadata.csv")
btcDiff <- read.csv("./datasets/BCHAIN-DIFF.csv")
btcHrate <- read.csv("./datasets/BCHAIN-HRATE.csv")
btcMkpru <- read.csv("./datasets/BCHAIN-MKPRU.csv")
btcTrvou <- read.csv("./datasets/BCHAIN-TRVOU.csv")
```

## Datasets Preparation

### Currency Exchange Rates

```{r tidy_currency}
CurrExchRatesClean <- currExchRates %>% select(which(colMeans(is.na(.)) < 0.2))
CurrExchRatesClean <- CurrExchRatesClean %>% mutate(Euro = ifelse(Date < as.Date("1998-10-30", format="%Y-%m-%d"), 0, Euro))
CurrExchRatesClean <- CurrExchRatesClean %>% mutate(Date = as.Date(Date, format= "%Y-%m-%d"))
CurrExchRatesClean <- na_ma(CurrExchRatesClean, k = 1)

st(CurrExchRatesClean)
```

### Gold Prices

```{r tidy_gold}
goldPricesClean <- goldPrices %>% mutate(
  EURO..AM. = ifelse(Date < as.Date("1998-12-31", format="%Y-%m-%d"), 0, EURO..AM.),
  EURO..PM. = ifelse(Date < as.Date("1998-12-31", format="%Y-%m-%d"), 0, EURO..PM.),
  USD..PM. = ifelse(Date < as.Date("1968-03-14", format="%Y-%m-%d"), 0, USD..PM.),
  GBP..PM. = ifelse(Date < as.Date("1968-03-14", format="%Y-%m-%d"), 0, GBP..PM.))

goldPricesClean <- goldPricesClean %>% mutate(Date = as.Date(Date, format= "%Y-%m-%d"))
goldPricesClean <- na_ma(goldPricesClean, k = 1)

st(goldPricesClean)
```

### World Development Index and Top Chosen Countries

```{r tidy_index, warning=FALSE}
#https://worldpopulationreview.com/country-rankings/developed-countries
hdiTop <- c('Norway', 'Ireland', 'Switzerland', 'Iceland', 'Hong Kong', 'Germany', 'Sweden', 'Netherlands', 'Australia', 'Denmark', 'Finland', 'Singapore', 'United Kingdom', 'New Zealand', 'Belgium', 'Canada', 'United States', 'Austria', 'Israel', 'Japan', 'Slovenia', 'Luxembourg', 'Korea, Rep.', 'Spain', 'France')

worldDevInd$Series.Name<-gsub("\\$","D",worldDevInd$Series.Name)

worldDevIndClean <- worldDevInd %>% select(-Series.Code) %>% 
  pivot_longer('X1970..YR1970.':'X2020..YR2020.', names_to = "Year", values_to = "Value", values_drop_na = FALSE) %>%
  pivot_wider(names_from = "Series.Name", values_from = Value) %>% unchop(everything())


worldDevIndClean <- worldDevIndClean %>% 
  mutate(Year = substr(Year, 2, 5)) %>% 
  filter(grepl('', Country.Code)) %>%
  relocate(Year, .after = Country.Code)


trial <- as.data.frame(worldDevIndClean)
trial <- worldDevIndClean %>% filter(Country.Name %in% hdiTop)
trial <- trial %>% select(which(colMeans(is.na(.)) < 0.20))
trial[is.na(trial)] <- 0
wdiTop <- trial

datatable(skim(wdiTop %>% dplyr::select(-Country.Name, -Country.Code, -Year)) %>% dplyr::select(skim_variable, numeric.mean, numeric.sd, numeric.p0, numeric.p25, numeric.p75, numeric.p100) %>% dplyr::rename(Variable=skim_variable, Mean=numeric.mean, "Std. Dev."=numeric.sd, Min=numeric.p0, "Pctl. 25"=numeric.p25, "Pctl. 75"=numeric.p75, Max=numeric.p100))
```

### S.P. Composite
```{r tidy_sp_composite}
spCompositeClean <- spComposite %>% 
  mutate(Cyclically.Adjusted.PE.Ratio = ifelse(Year < as.Date("1880-12-31", format="%Y-%m-%d"), 0, Cyclically.Adjusted.PE.Ratio)) %>% rename(Date = Year)
spCompositeClean <- spCompositeClean%>% mutate(Date = as.Date(Date, format= "%Y-%m-%d"))
spCompositeClean <- na_ma(spCompositeClean, k = 1)

st(spComposite)
```

### Bitcoins' Data
```{r tidy_bitcoin, echo=TRUE, message=FALSE, warning=FALSE}
btcTrvou <- btcTrvou %>% rename(Trvou = Value)
btcMkpru <- btcMkpru %>% rename(Mkpru = Value)
btcDiff <- btcDiff %>% rename(Diff = Value)
btcHrate <- btcHrate %>% rename(Hrate = Value)
btcAllClean <- btcTrvou %>% left_join(btcMkpru) %>% left_join(btcHrate) %>% left_join(btcDiff)
btcAllClean <- btcAllClean %>% mutate(Date = as.Date(Date, format= "%Y-%m-%d"))
btcAllClean <- na_ma(btcAllClean, k = 1)

st(btcAllClean)
```

```{r bitcoin_graphs}

btcAnalysis <- btcAllClean %>% pivot_longer(cols='Trvou':'Diff', names_to = 'Param', values_to = 'Value')
ggplot(btcAnalysis, aes(x=Date, y=Value, color = as.factor(Param))) + geom_line() + facet_wrap(~Param, scales = "free_y") + theme_minimal() + labs(colour = "Bitcoin's Parameter", title = "Bitcoin's Overview")
```


## Attributes analysis
```{r attr_analysis_wdi, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}

#https://worldpopulationreview.com/country-rankings/developed-countries

example2019 <- wdiTop %>% filter(Year == 2019)

ggplot(data = example2019, aes(x = Country.Name, y =`Urban population growth (annual %)`, fill=as.factor(Country.Name))) +
    geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

ggplot(data = example2019, aes(x = Country.Name, y = `Trade (% of GDP)`, fill=as.factor(Country.Name))) +
    geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

ggplot(data = example2019, aes(x = Country.Name, y = `Total natural resources rents (% of GDP)`, fill=as.factor(Country.Name))) +
    geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

ggplot(data = example2019, aes(x = Country.Name, y = `Population, total`, fill=as.factor(Country.Name))) +
    geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

ggplot(data = example2019, aes(x = Country.Name, y = `Net primary income (Net income from abroad) (current USD)`, fill=as.factor(Country.Name))) + geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

ggplot(data = example2019, aes(x = Country.Name, y = `Birth rate, crude (per 1,000 people)`, fill=as.factor(Country.Name))) +
    geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

ggplot(data = example2019, aes(x = Country.Name, y = `GDP (current USD)`, fill=as.factor(Country.Name))) +
    geom_bar(stat = "identity") + coord_flip() + theme_minimal() + labs(fill='Country', x='Country')

```

```{r attr_analysis_gold}

GoldAnalysis <- goldPricesClean %>% pivot_longer(cols = 'USD..AM.':'EURO..PM.', names_to = 'Curr', values_to = 'Value')
ggplot(data = GoldAnalysis, aes(x = Date, y = Value, color=as.factor(Curr))) +
    geom_point(size=0.1) + facet_wrap(~Curr) + theme_minimal() + labs(color='Currency', title='Gold Prices\' Overview')

```
```{r attr_analysis_spcomposite, echo=FALSE, message=FALSE, warning=FALSE}
spAnalysis <- spCompositeClean %>% pivot_longer(cols='S.P.Composite':'Cyclically.Adjusted.PE.Ratio', values_to = 'Value', names_to = 'Param')

earn <- spAnalysis %>% filter(Param %in% c('Earnings', 'Real.Earnings'))
ggplot(data = earn, aes(x = Date, y = Value, color=as.factor(Param))) +
    geom_line() + facet_wrap(~Param) + labs(color='Type of Earnings') + theme_minimal() + transition_reveal(Date)


```
```{r echo=FALSE, message=FALSE, warning=FALSE}
earn <- spAnalysis %>% filter(Param %in% c('Dividend', 'Real.Dividend'))
ggplot(data = earn, aes(x = Date, y = Value, color=as.factor(Param))) +
    geom_line() + facet_wrap(~Param) + labs(color='Type of Dividend') + theme_minimal() + transition_reveal(Date)
```
```{r}
ggplot(data = spCompositeClean, aes(x = Date, y = S.P.Composite)) +
    geom_line(color='blue') + theme_minimal() + labs(title='S.P.Composite through Years') + transition_reveal(Date)
```



## Interesting Corelations for Bitcoin's data
```{r corelations}

btcPlusSP <- btcAllClean %>% inner_join(spCompositeClean, on='Date')
btcPlusGold <- btcAllClean %>% inner_join(goldPricesClean, on='Date')

#cor(btcAllClean$Mkpru, btcAllClean$Hrate,  method = "pearson", use = "complete.obs")

ggscatter(btcAllClean, x = "Mkpru", y = "Hrate", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Mkpru", ylab = "Hrate", color = 'plum4')

#cor(btcPlusSP$Mkpru,btcPlusSP$"S.P.Composite", method = "pearson", use = "complete.obs")

ggscatter(btcPlusSP, x = "Mkpru", y = "S.P.Composite", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Mkpru", ylab = "S.P.Composite", color='maroon2')

#cor(btcPlusSP$Mkpru,btcPlusSP$"CPI", method = "pearson", use = "complete.obs")

ggscatter(btcPlusSP, x = "Mkpru", y = "CPI", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Mkpru", ylab = "CPI", color='indianred3')


# ggscatter(btcPlusGold, x = "Mkpru", y = "USD..AM.", 
#           add = "reg.line", conf.int = TRUE, 
#           cor.coef = TRUE, cor.method = "pearson",
#           xlab = "Mkpru", ylab = "USD..AM.", color='coral2')


```



## Model
```{r model}

set.seed(23)

btcAllClean2 <- btcAllClean %>% select(-Date)

inTraining <- createDataPartition(y = btcAllClean2$Mkpru, p = .70, list = FALSE)
train <- btcAllClean2[inTraining,]
valid_and_test  <- btcAllClean2[-inTraining,]

inTesting <- createDataPartition(y = valid_and_test$Mkpru, p = .50, list = FALSE)
valid <- valid_and_test[ -inTesting,]
test <- valid_and_test[ inTesting,]


ctrl <- trainControl(
    # powtórzona ocena krzyżowa
    method = "repeatedcv",
    # liczba podziałów
    number = 2,
    # liczba powtórzeń
    repeats = 5)


fit <- train(Mkpru ~ .,
             data = train,
             method = "rf",
             trControl = ctrl,
             # Paramter dla algorytmu uczącego
             ntree = 10)

fit

pred <- predict(fit, newdata = test)
preddf <- data.frame(Pred = pred, Mkpru = test$Mkpru)

View(preddf)
```






